version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: passwr0d
    ports:
      - 5432:5432

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379